org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.workers.max=4

# ----------------------------------------------------------------

minecraft_version=26.2
java_version=25

# ----------------------------------------------------------------

maven_group=virtuoel
archives_base_name=Pehkui
mod_id=pehkui
mod_name=Pehkui
mod_version=3.8.3+26.2
mod_license=MIT
mod_description=Allows resizing of most entities.

homepage_url=https://github.com/fmpapierz/Pehkui-Updated
issues_url=https://github.com/fmpapierz/Pehkui-Updated/issues
sources_url=https://github.com/fmpapierz/Pehkui-Updated

# ----------------------------------------------------------------

fabric_loader_version=0.19.5
fabric_api_version=0.160.0+26.2
quilt_loader_version=0.31.0-beta.4
neo_version=26.2.0.82
forge_version=26.2-65.1.3
modmenu_version=20.0.2

net.minecraftforge.gradle.merge-source-sets=true
